name: NPM Publish

env:
  NODE_VERSION: 18

on:
  push:
    tags: v*

permissions:
  contents: read

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          registry-url: https://registry.npmjs.org/
          cache: npm

      - run: npm ci
      - run: npm run build
        env:
          NODE_ENV: production

      - name: Publish to NPM
        run: npm publish dist/angular-paginator/
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
